name: Test Multi-Platform Build

on:
  pull_request:
    paths:
      - "Dockerfile"
      - "go.mod"
      - "go.sum"
      - "**.go"
      - ".github/workflows/test-build.yml"

jobs:
  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for ${{ matrix.platform }}
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ovs-port-manager:test-${{ matrix.platform }}

      - name: Test image functionality
        if: matrix.platform == 'linux/amd64'
        run: |
          docker buildx build --platform ${{ matrix.platform }} --load -t ovs-port-manager:test .
          # Test that the binary exists and is executable
          docker run --rm ovs-port-manager:test --help || true
